// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.core.util;

@net.sf.jni4net.attributes.ClrType
public class ConsoleOut extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ConsoleOut(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public ConsoleOut() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        gamelib.core.util.ConsoleOut.__ctorConsoleOut0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorConsoleOut0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()[LGameLib/Core/Util/Message;")
    public native static gamelib.core.util.Message[] getAllMessages();
    
    @net.sf.jni4net.attributes.ClrMethod("([LGameLib/Core/Util/MessageType;)V")
    public native static void SetRestriction(gamelib.core.util.MessageType[] types);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;I)V")
    public native static void Log(java.lang.String text, java.lang.String memberName, java.lang.String filePath, int lineNumber);
    
    @net.sf.jni4net.attributes.ClrMethod("(LGameLib/Core/Util/MessageType;LSystem/String;LSystem/String;LSystem/String;I)V")
    public native static void Log(gamelib.core.util.MessageType type, java.lang.String text, java.lang.String memberName, java.lang.String filePath, int lineNumber);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;I)V")
    public native static void Information(java.lang.String text, java.lang.String memberName, java.lang.String filePath, int lineNumber);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;I)V")
    public native static void Debug(java.lang.String text, java.lang.String memberName, java.lang.String filePath, int lineNumber);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;I)V")
    public native static void Warning(java.lang.String text, java.lang.String memberName, java.lang.String filePath, int lineNumber);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;I)V")
    public native static void Error(java.lang.String text, java.lang.String memberName, java.lang.String filePath, int lineNumber);
    
    public static system.Type typeof() {
        return gamelib.core.util.ConsoleOut.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.core.util.ConsoleOut.staticType = staticType;
    }
    //</generated-proxy>
}
