// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.core.util;

@net.sf.jni4net.attributes.ClrType
public class Converter extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Converter(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected Converter() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LGameLib/Core/Base/PlayerColor2P;)LGameLib/Core/Base/PlayerColor2P;")
    public native static gamelib.core.base.PlayerColor2P Reverse(gamelib.core.base.PlayerColor2P pc2p);
    
    @net.sf.jni4net.attributes.ClrMethod("(LGameLib/Core/Base/PlayerColor2P;)I")
    public native static int ToInt(gamelib.core.base.PlayerColor2P color);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)LGameLib/Core/Base/PlayerColor2P;")
    public native static gamelib.core.base.PlayerColor2P ToPlayerColor2P(int color);
    
    public static system.Type typeof() {
        return gamelib.core.util.Converter.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.core.util.Converter.staticType = staticType;
    }
    //</generated-proxy>
}
