// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.core.util;

@net.sf.jni4net.attributes.ClrType
public class Message extends system.ValueType {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Message(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/String;LSystem/String;LSystem/String;ILGameLib/Core/Util/MessageType;)V")
    public Message(java.lang.String messageText, java.lang.String sourceProperty, java.lang.String sourceFile, int sourceLine, gamelib.core.util.MessageType type) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        gamelib.core.util.Message.__ctorMessage0(this, messageText, sourceProperty, sourceFile, sourceLine, type);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILgamelib/core/util/MessageType;)V")
    private native static void __ctorMessage0(net.sf.jni4net.inj.IClrProxy thiz, java.lang.String messageText, java.lang.String sourceProperty, java.lang.String sourceFile, int sourceLine, gamelib.core.util.MessageType type);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/DateTime;")
    public native system.DateTime getTime();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getSourceProperty();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getSourceFile();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getSourceLine();
    
    @net.sf.jni4net.attributes.ClrMethod("()LGameLib/Core/Util/MessageType;")
    public native gamelib.core.util.MessageType getType();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getMessageText();
    
    public static system.Type typeof() {
        return gamelib.core.util.Message.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.core.util.Message.staticType = staticType;
    }
    //</generated-proxy>
}
