// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.core.util;

@net.sf.jni4net.attributes.ClrType
public class RawColumn extends system.ValueType implements gamelib.api.IInputObjectContainer {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected RawColumn(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(II)V")
    public RawColumn(int Raw, int Column) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        gamelib.core.util.RawColumn.__ctorRawColumn0(this, Raw, Column);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("([[[LSystem/ValueTuple`2;)V")
    public RawColumn(system.ValueType value) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        gamelib.core.util.RawColumn.__ctorRawColumn1(this, value);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LGameLib/Core/Util/RawColumn;)V")
    public RawColumn(gamelib.core.util.RawColumn value) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        gamelib.core.util.RawColumn.__ctorRawColumn2(this, value);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(II)V")
    private native static void __ctorRawColumn0(net.sf.jni4net.inj.IClrProxy thiz, int Raw, int Column);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lsystem/ValueType;)V")
    private native static void __ctorRawColumn1(net.sf.jni4net.inj.IClrProxy thiz, system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lgamelib/core/util/RawColumn;)V")
    private native static void __ctorRawColumn2(net.sf.jni4net.inj.IClrProxy thiz, gamelib.core.util.RawColumn value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LGameLib/Core/Util/RawColumn;)I")
    public native int CompareTo(gamelib.core.util.RawColumn other);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getRaw();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setRaw(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getColumn();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setColumn(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getX();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setX(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getY();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setY(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getWidth();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setWidth(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getHeight();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setHeight(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getHorizontal();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setHorizontal(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getVertical();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setVertical(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()[[[LSystem/ValueTuple`2;")
    public native system.ValueType getTuple();
    
    @net.sf.jni4net.attributes.ClrMethod("(II)LGameLib/Core/Util/RawColumn;")
    public native static gamelib.core.util.RawColumn New(int Raw, int Column);
    
    @net.sf.jni4net.attributes.ClrMethod("([[[LSystem/ValueTuple`2;)LGameLib/Core/Util/RawColumn;")
    public native static gamelib.core.util.RawColumn New(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LGameLib/Core/Util/RawColumn;)LGameLib/Core/Util/RawColumn;")
    public native static gamelib.core.util.RawColumn New(gamelib.core.util.RawColumn value);
    
    public static system.Type typeof() {
        return gamelib.core.util.RawColumn.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.core.util.RawColumn.staticType = staticType;
    }
    //</generated-proxy>
}
