// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.core.util;

@net.sf.jni4net.attributes.ClrType
public class RawColumnUtil extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected RawColumnUtil(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected RawColumnUtil() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    public static system.Type typeof() {
        return gamelib.core.util.RawColumnUtil.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.core.util.RawColumnUtil.staticType = staticType;
    }
    //</generated-proxy>
}
