// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.core.util;

@net.sf.jni4net.attributes.ClrType
public class SafeArray`1 extends system.ValueType {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected SafeArray`1(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(I)V")
    public SafeArray`1(int length) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        gamelib.core.util.SafeArray`1.__ctorSafeArray`10(this, length);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    private native static void __ctorSafeArray`10(net.sf.jni4net.inj.IClrProxy thiz, int length);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getLength();
    
    @net.sf.jni4net.attributes.ClrMethod("()[L;")
    public native system.Object[] getArray();
    
    @net.sf.jni4net.attributes.ClrMethod("(II)")
    public native system.Object getItem(int x, int y);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String Debug();
    
    public static system.Type typeof() {
        return gamelib.core.util.SafeArray`1.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.core.util.SafeArray`1.staticType = staticType;
    }
    //</generated-proxy>
}
