// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.api;

@net.sf.jni4net.attributes.ClrType
public class GameInputter extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected GameInputter(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected GameInputter() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String Name();
    
    @net.sf.jni4net.attributes.ClrMethod("(LGameLib/API/GameField;)LGameLib/API/IInputObjectContainer;")
    public native gamelib.api.IInputObjectContainer Input(gamelib.api.GameField field);
    
    public static system.Type typeof() {
        return gamelib.api.GameInputter.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.api.GameInputter.staticType = staticType;
    }
    //</generated-proxy>
}
