// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.api;

@net.sf.jni4net.attributes.ClrType
public class GameAddonAttribute extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected GameAddonAttribute(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/String;)V")
    public GameAddonAttribute(java.lang.String gameid) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        gamelib.api.GameAddonAttribute.__ctorGameAddonAttribute0(this, gameid);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)V")
    private native static void __ctorGameAddonAttribute0(net.sf.jni4net.inj.IClrProxy thiz, java.lang.String gameid);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getGameID();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setGameID(java.lang.String value);
    
    public static system.Type typeof() {
        return gamelib.api.GameAddonAttribute.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.api.GameAddonAttribute.staticType = staticType;
    }
    //</generated-proxy>
}
