// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.api;

@net.sf.jni4net.attributes.ClrInterface
public interface IDrawer {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("(LGameLib/Core/Base/GridField;)V")
    void DrawPanel(gamelib.core.base.GridField field);
    
    @net.sf.jni4net.attributes.ClrMethod("(LGameLib/Core/Base/GridField;)V")
    void DrawConsole(gamelib.core.base.GridField field);
    //</generated-interface>
}
