// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.api;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class IInputObjectContainer_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return gamelib.api.IInputObjectContainer_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.api.IInputObjectContainer_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __IInputObjectContainer extends system.Object implements gamelib.api.IInputObjectContainer {
    
    protected __IInputObjectContainer(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
}
//</generated-proxy>
