// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.api;

@net.sf.jni4net.attributes.ClrType
public class LibraryObject extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected LibraryObject(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/String;)V")
    public LibraryObject(java.lang.String path) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        gamelib.api.LibraryObject.__ctorLibraryObject0(this, path);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)V")
    private native static void __ctorLibraryObject0(net.sf.jni4net.inj.IClrProxy thiz, java.lang.String path);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getID();
    
    @net.sf.jni4net.attributes.ClrMethod("()LGameLib/API/LibraryType;")
    public native gamelib.api.LibraryType getLibType();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Reflection/Assembly;")
    public native system.reflection.Assembly getAsm();
    
    public static system.Type typeof() {
        return gamelib.api.LibraryObject.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.api.LibraryObject.staticType = staticType;
    }
    //</generated-proxy>
}
