// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.api;

@net.sf.jni4net.attributes.ClrType
public class Util extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Util(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected Util() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(I)I")
    public native static int DICE(int f);
    
    @net.sf.jni4net.attributes.ClrMethod("(II)I")
    public native static int Random(int a, int b);
    
    @net.sf.jni4net.attributes.ClrMethod("([[LSystem/Collections/Generic/IEnumerable`1;)LGameLib/Core/Util/RawColumn;")
    public native static gamelib.core.util.RawColumn Random(system.collections.IEnumerable source);
    
    @net.sf.jni4net.attributes.ClrMethod("([LGameLib/Core/Util/RawColumn;[LGameLib/Core/Util/RawColumn;Z)Z")
    public native static boolean Include(gamelib.core.util.RawColumn[] source, gamelib.core.util.RawColumn[] target, boolean strict);
    
    public static system.Type typeof() {
        return gamelib.api.Util.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.api.Util.staticType = staticType;
    }
    //</generated-proxy>
}
