//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLib.Core.Util {
    
    
    #region Component Designer generated code 
    public partial class ConsoleOut_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::GameLib.Core.Util.@__ConsoleOut.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::GameLib.Core.Util.ConsoleOut), typeof(global::GameLib.Core.Util.ConsoleOut_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::GameLib.Core.Util.ConsoleOut), typeof(global::GameLib.Core.Util.ConsoleOut_))]
    internal sealed partial class @__ConsoleOut : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__ConsoleOut(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::GameLib.Core.Util.@__ConsoleOut.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ConsoleOut);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAllMessages", "AllMessages0", "()[Lgamelib/core/util/Message;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SetRestriction", "SetRestriction1", "([Lgamelib/core/util/MessageType;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Log", "Log2", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Log", "Log3", "(Lgamelib/core/util/MessageType;Ljava/lang/String;Ljava/lang/String;Ljava/lang/St" +
                        "ring;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Information", "Information4", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Debug", "Debug5", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Warning", "Warning6", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Error", "Error7", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorConsoleOut0", "__ctorConsoleOut0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle AllMessages0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class) {
            // ()[Lgamelib/core/util/Message;
            // ()[LGameLib/Core/Util/Message;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::GameLib.Core.Util.Message[], global::GameLib.Core.Util.Message>(@__env, global::GameLib.Core.Util.ConsoleOut.AllMessages);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void SetRestriction1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle types) {
            // ([Lgamelib/core/util/MessageType;)V
            // ([LGameLib/Core/Util/MessageType;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.Util.ConsoleOut.SetRestriction(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::GameLib.Core.Util.MessageType[], global::GameLib.Core.Util.MessageType>(@__env, types));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Log2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle text, global::net.sf.jni4net.utils.JniLocalHandle memberName, global::net.sf.jni4net.utils.JniLocalHandle filePath, int lineNumber) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
            // (LSystem/String;LSystem/String;LSystem/String;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.Util.ConsoleOut.Log(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, text), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, memberName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, filePath), lineNumber);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Log3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle type, global::net.sf.jni4net.utils.JniLocalHandle text, global::net.sf.jni4net.utils.JniLocalHandle memberName, global::net.sf.jni4net.utils.JniLocalHandle filePath, int lineNumber) {
            // (Lgamelib/core/util/MessageType;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
            // (LGameLib/Core/Util/MessageType;LSystem/String;LSystem/String;LSystem/String;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.Util.ConsoleOut.Log(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.Util.MessageType>(@__env, type), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, text), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, memberName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, filePath), lineNumber);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Information4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle text, global::net.sf.jni4net.utils.JniLocalHandle memberName, global::net.sf.jni4net.utils.JniLocalHandle filePath, int lineNumber) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
            // (LSystem/String;LSystem/String;LSystem/String;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.Util.ConsoleOut.Information(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, text), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, memberName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, filePath), lineNumber);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Debug5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle text, global::net.sf.jni4net.utils.JniLocalHandle memberName, global::net.sf.jni4net.utils.JniLocalHandle filePath, int lineNumber) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
            // (LSystem/String;LSystem/String;LSystem/String;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.Util.ConsoleOut.Debug(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, text), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, memberName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, filePath), lineNumber);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Warning6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle text, global::net.sf.jni4net.utils.JniLocalHandle memberName, global::net.sf.jni4net.utils.JniLocalHandle filePath, int lineNumber) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
            // (LSystem/String;LSystem/String;LSystem/String;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.Util.ConsoleOut.Warning(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, text), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, memberName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, filePath), lineNumber);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Error7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle text, global::net.sf.jni4net.utils.JniLocalHandle memberName, global::net.sf.jni4net.utils.JniLocalHandle filePath, int lineNumber) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
            // (LSystem/String;LSystem/String;LSystem/String;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.Util.ConsoleOut.Error(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, text), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, memberName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, filePath), lineNumber);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorConsoleOut0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.Util.ConsoleOut @__real = new global::GameLib.Core.Util.ConsoleOut();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::GameLib.Core.Util.@__ConsoleOut(@__env);
            }
        }
    }
    #endregion
}
