//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLib.Core.Util {
    
    
    #region Component Designer generated code 
    public partial class Converter_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::GameLib.Core.Util.@__Converter.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::GameLib.Core.Util.Converter), typeof(global::GameLib.Core.Util.Converter_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::GameLib.Core.Util.Converter), typeof(global::GameLib.Core.Util.Converter_))]
    internal sealed partial class @__Converter : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Converter(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::GameLib.Core.Util.@__Converter.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Converter);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Reverse", "Reverse0", "(Lgamelib/core/base/PlayerColor2P;)Lgamelib/core/base/PlayerColor2P;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToInt", "ToInt1", "(Lgamelib/core/base/PlayerColor2P;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToPlayerColor2P", "ToPlayerColor2P2", "(I)Lgamelib/core/base/PlayerColor2P;"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Reverse0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle pc2p) {
            // (Lgamelib/core/base/PlayerColor2P;)Lgamelib/core/base/PlayerColor2P;
            // (LGameLib/Core/Base/PlayerColor2P;)LGameLib/Core/Base/PlayerColor2P;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::GameLib.Core.Base.PlayerColor2P>(@__env, global::GameLib.Core.Util.Converter.Reverse(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.Base.PlayerColor2P>(@__env, pc2p)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int ToInt1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle color) {
            // (Lgamelib/core/base/PlayerColor2P;)I
            // (LGameLib/Core/Base/PlayerColor2P;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            @__return = ((int)(global::GameLib.Core.Util.Converter.ToInt(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.Base.PlayerColor2P>(@__env, color))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ToPlayerColor2P2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, int color) {
            // (I)Lgamelib/core/base/PlayerColor2P;
            // (I)LGameLib/Core/Base/PlayerColor2P;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::GameLib.Core.Base.PlayerColor2P>(@__env, global::GameLib.Core.Util.Converter.ToPlayerColor2P(color));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::GameLib.Core.Util.@__Converter(@__env);
            }
        }
    }
    #endregion
}
