//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLib.Core {
    
    
    #region Component Designer generated code 
    public partial class BordGame_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::GameLib.Core.@__BordGame.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::GameLib.Core.BordGame), typeof(global::GameLib.Core.BordGame_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::GameLib.Core.BordGame), typeof(global::GameLib.Core.BordGame_))]
    internal sealed partial class @__BordGame : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__BordGame(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::GameLib.Core.@__BordGame.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__BordGame);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SetPlayer", "SetPlayer0", "(Lsystem/Type;Lsystem/Type;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Draw", "Draw1", "()V"));
            return methods;
        }
        
        private static void SetPlayer0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle pl1, global::net.sf.jni4net.utils.JniLocalHandle pl2) {
            // (Lsystem/Type;Lsystem/Type;)V
            // (LSystem/Type;LSystem/Type;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.BordGame @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.BordGame>(@__env, @__obj);
            @__real.SetPlayer(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Type>(@__env, pl1), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Type>(@__env, pl2));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Draw1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.BordGame @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.BordGame>(@__env, @__obj);
            @__real.Draw();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::GameLib.Core.@__BordGame(@__env);
            }
        }
    }
    #endregion
}
