//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLib.Core {
    
    
    #region Component Designer generated code 
    public partial class SingleGame_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::GameLib.Core.@__SingleGame.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::GameLib.Core.SingleGame), typeof(global::GameLib.Core.SingleGame_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::GameLib.Core.SingleGame), typeof(global::GameLib.Core.SingleGame_))]
    internal sealed partial class @__SingleGame : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__SingleGame(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::GameLib.Core.@__SingleGame.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__SingleGame);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "addOnDraw", "OnDraw0", "(Lsystem/MulticastDelegate;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "removeOnDraw", "OnDraw1", "(Lsystem/MulticastDelegate;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "addOnInput", "OnInput2", "(Lsystem/MulticastDelegate;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "removeOnInput", "OnInput3", "(Lsystem/MulticastDelegate;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Start", "Start4", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "UpDate", "UpDate5", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "End", "End6", "()V"));
            return methods;
        }
        
        private static void OnDraw0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/MulticastDelegate;)V
            // (LGameLib/Core/SingleGame+OnDrawHandler;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.SingleGame @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.SingleGame>(@__env, @__obj);
            @__real.OnDraw += global::net.sf.jni4net.utils.Convertor.StrongJ2CpDelegate<global::GameLib.Core.SingleGame.OnDrawHandler>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void OnDraw1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/MulticastDelegate;)V
            // (LGameLib/Core/SingleGame+OnDrawHandler;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.SingleGame @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.SingleGame>(@__env, @__obj);
            @__real.OnDraw -= global::net.sf.jni4net.utils.Convertor.StrongJ2CpDelegate<global::GameLib.Core.SingleGame.OnDrawHandler>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void OnInput2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/MulticastDelegate;)V
            // (LGameLib/Core/SingleGame+OnInputHandler;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.SingleGame @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.SingleGame>(@__env, @__obj);
            @__real.OnInput += global::net.sf.jni4net.utils.Convertor.StrongJ2CpDelegate<global::GameLib.Core.SingleGame.OnInputHandler>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void OnInput3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/MulticastDelegate;)V
            // (LGameLib/Core/SingleGame+OnInputHandler;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.SingleGame @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.SingleGame>(@__env, @__obj);
            @__real.OnInput -= global::net.sf.jni4net.utils.Convertor.StrongJ2CpDelegate<global::GameLib.Core.SingleGame.OnInputHandler>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Start4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.SingleGame @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.SingleGame>(@__env, @__obj);
            @__real.Start();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void UpDate5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.SingleGame @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.SingleGame>(@__env, @__obj);
            @__real.UpDate();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void End6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.Core.SingleGame @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.Core.SingleGame>(@__env, @__obj);
            @__real.End();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::GameLib.Core.@__SingleGame(@__env);
            }
        }
    }
    #endregion
}
