// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package gamelib.core;

@net.sf.jni4net.attributes.ClrType
public class OnDrawArgs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected OnDrawArgs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public OnDrawArgs() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        gamelib.core.OnDrawArgs.__ctorOnDrawArgs0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorOnDrawArgs0(net.sf.jni4net.inj.IClrProxy thiz);
    
    public static system.Type typeof() {
        return gamelib.core.OnDrawArgs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        gamelib.core.OnDrawArgs.staticType = staticType;
    }
    //</generated-proxy>
}
