// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package rutil;

@net.sf.jni4net.attributes.ClrType
public class Decimal32 extends system.ValueType {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Decimal32(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/String;)V")
    public Decimal32(java.lang.String value) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        rutil.Decimal32.__ctorDecimal320(this, value);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/Decimal;)V")
    public Decimal32(system.Decimal value) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        rutil.Decimal32.__ctorDecimal321(this, value);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)V")
    private native static void __ctorDecimal320(net.sf.jni4net.inj.IClrProxy thiz, java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lsystem/Decimal;)V")
    private native static void __ctorDecimal321(net.sf.jni4net.inj.IClrProxy thiz, system.Decimal value);
    
    public static system.Type typeof() {
        return rutil.Decimal32.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        rutil.Decimal32.staticType = staticType;
    }
    //</generated-proxy>
}
