// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package rutil;

@net.sf.jni4net.attributes.ClrType
public class IO extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected IO(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected IO() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/Text/Encoding;)V")
    public native static void FileWriteText(java.lang.String source, java.lang.String fileName, system.Object encode);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;[[LSystem/Collections/Generic/IEnumerable`1;)V")
    public native static void WriteFile(java.lang.String filename, system.collections.IEnumerable contents);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/String;")
    public native static java.lang.String ReadFile(java.lang.String filename);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;Z)[[[[[LSystem/Collections/Generic/Dictionary`2;")
    public native static system.Object ReadCSV(java.lang.String fileName, boolean titleRaw);
    
    public static system.Type typeof() {
        return rutil.IO.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        rutil.IO.staticType = staticType;
    }
    //</generated-proxy>
}
