// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package rutil;

@net.sf.jni4net.attributes.ClrType
public class Utility extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Utility(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected Utility() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    public static java.lang.Iterable<system.Type> GetBaseTypesIterable(system.Type self) {
        return new mitza.jni4net.wrapper.Iterable<system.Type>(GetBaseTypes(self));
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Type;)[[LSystem/Collections/Generic/IEnumerable`1;")
    public native static system.collections.IEnumerable GetBaseTypes(system.Type self);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LRUtil/Utility+PadType;I)LSystem/String;")
    public native static java.lang.String PadLeftInBytes(java.lang.String value, system.Enum type, int byteCount);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LRUtil/Utility+PadType;I)LSystem/String;")
    public native static java.lang.String PadRightInBytes(java.lang.String value, system.Enum type, int byteCount);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;ZCC)[LSystem/String;")
    public native static java.lang.String[] Split(java.lang.String source, boolean isArgs, char separator, char blocker);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/Text/RegularExpressions/RegexOptions;)[LSystem/String;")
    public native static java.lang.String[] Split(java.lang.String source, java.lang.String pattern, system.Enum option);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;)LSystem/String;")
    public native static java.lang.String Replace(java.lang.String source, java.lang.String pattern, java.lang.String replacement);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)I")
    public native static int ParseInt(java.lang.String source);
    
    @net.sf.jni4net.attributes.ClrMethod("([[LSystem/Collections/Generic/IEnumerable`1;)LSystem/String;")
    public native static java.lang.String ParseString(system.collections.IEnumerable source);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)D")
    public native static double ParseDouble(java.lang.String source);
    
    @net.sf.jni4net.attributes.ClrMethod("(D)I")
    public native static int Round(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("(D)I")
    public native static int RoundDown(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("(D)I")
    public native static int RoundUp(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("(JJ)[[[LSystem/Tuple`2;")
    public native static system.Object Div(long left, long right);
    
    @net.sf.jni4net.attributes.ClrMethod("(DD)[[[LSystem/Tuple`2;")
    public native static system.Object Div(double left, double right);
    
    @net.sf.jni4net.attributes.ClrMethod("(D)D")
    public native static double ToRadian(double angle);
    
    @net.sf.jni4net.attributes.ClrMethod("(D)D")
    public native static double ToAngle(double radian);
    
    @net.sf.jni4net.attributes.ClrMethod("(D[[[LSystem/ValueTuple`2;)Z")
    public native static boolean ToFraction(double value, net.sf.jni4net.Out<system.ValueType> result);
    
    @net.sf.jni4net.attributes.ClrMethod("(JJ)[[[LSystem/ValueTuple`2;")
    public native static system.ValueType Reduction(long numerator, long denominator);
    
    @net.sf.jni4net.attributes.ClrMethod("(JJ)J")
    public native static long Gcd(long a, long b);
    
    @net.sf.jni4net.attributes.ClrMethod("([[[LSystem/Func`2;)[[LSystem/Collections/Generic/IEnumerable`1;")
    public native static system.collections.IEnumerable PrimeNumber(system.MulticastDelegate conditions);
    
    @net.sf.jni4net.attributes.ClrMethod("(DDDD)D")
    public native static double Distance(double x1, double y1, double x2, double y2);
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)Z")
    public native static boolean Toggle(net.sf.jni4net.Ref<java.lang.Boolean> value);
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)Z")
    public native static boolean Not(boolean value);
    
    public static system.Type typeof() {
        return rutil.Utility.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        rutil.Utility.staticType = staticType;
    }
    //</generated-proxy>
}
