//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLib.API {
    
    
    #region Component Designer generated code 
    public partial class LibraryLoader_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::GameLib.API.@__LibraryLoader.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::GameLib.API.LibraryLoader), typeof(global::GameLib.API.LibraryLoader_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::GameLib.API.LibraryLoader), typeof(global::GameLib.API.LibraryLoader_))]
    internal sealed partial class @__LibraryLoader : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__LibraryLoader(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::GameLib.API.@__LibraryLoader.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__LibraryLoader);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getLibs", "Libs0", "()[Lgamelib/api/LibraryObject;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getGames", "Games1", "()[Lsystem/reflection/Assembly;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getInputters", "Inputters2", "()[Lsystem/reflection/Assembly;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Inpuuters", "Inpuuters3", "(Ljava/lang/String;)[Lsystem/reflection/Assembly;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "LoadFile", "LoadFile4", "(Ljava/lang/String;)Lgamelib/api/LibraryObject;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "LoadFolder", "LoadFolder5", "(Ljava/lang/String;)[Lgamelib/api/LibraryObject;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorLibraryLoader0", "__ctorLibraryLoader0", "(Lnet/sf/jni4net/inj/IClrProxy;Ljava/lang/String;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Libs0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lgamelib/api/LibraryObject;
            // ()[LGameLib/API/LibraryObject;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::GameLib.API.LibraryLoader @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.API.LibraryLoader>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::GameLib.API.LibraryObject[], global::GameLib.API.LibraryObject>(@__env, @__real.Libs);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Games1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lsystem/reflection/Assembly;
            // ()[LSystem/Reflection/Assembly;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::GameLib.API.LibraryLoader @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.API.LibraryLoader>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::System.Reflection.Assembly[], global::System.Reflection.Assembly>(@__env, @__real.Games);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Inputters2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lsystem/reflection/Assembly;
            // ()[LSystem/Reflection/Assembly;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::GameLib.API.LibraryLoader @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.API.LibraryLoader>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::System.Reflection.Assembly[], global::System.Reflection.Assembly>(@__env, @__real.Inputters);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Inpuuters3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle id) {
            // (Ljava/lang/String;)[Lsystem/reflection/Assembly;
            // (LSystem/String;)[LSystem/Reflection/Assembly;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::GameLib.API.LibraryLoader @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::GameLib.API.LibraryLoader>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::System.Reflection.Assembly[], global::System.Reflection.Assembly>(@__env, @__real.Inpuuters(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, id)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle LoadFile4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle file) {
            // (Ljava/lang/String;)Lgamelib/api/LibraryObject;
            // (LSystem/String;)LGameLib/API/LibraryObject;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::GameLib.API.LibraryObject>(@__env, global::GameLib.API.LibraryLoader.LoadFile(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, file)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle LoadFolder5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle folder) {
            // (Ljava/lang/String;)[Lgamelib/api/LibraryObject;
            // (LSystem/String;)[LGameLib/API/LibraryObject;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::GameLib.API.LibraryObject[], global::GameLib.API.LibraryObject>(@__env, global::GameLib.API.LibraryLoader.LoadFolder(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, folder)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorLibraryLoader0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle path) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::GameLib.API.LibraryLoader @__real = new global::GameLib.API.LibraryLoader(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, path));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::GameLib.API.@__LibraryLoader(@__env);
            }
        }
    }
    #endregion
}
