//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RUtil {
    
    
    #region Component Designer generated code 
    public partial class IO_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::RUtil.@__IO.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::RUtil.IO), typeof(global::RUtil.IO_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::RUtil.IO), typeof(global::RUtil.IO_))]
    internal sealed partial class @__IO : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__IO(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::RUtil.@__IO.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__IO);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "FileWriteText", "FileWriteText0", "(Ljava/lang/String;Ljava/lang/String;Lsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "WriteFile", "WriteFile1", "(Ljava/lang/String;Lsystem/collections/IEnumerable;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ReadFile", "ReadFile2", "(Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ReadCSV", "ReadCSV3", "(Ljava/lang/String;Z)Lsystem/Object;"));
            return methods;
        }
        
        private static void FileWriteText0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle source, global::net.sf.jni4net.utils.JniLocalHandle fileName, global::net.sf.jni4net.utils.JniLocalHandle encode) {
            // (Ljava/lang/String;Ljava/lang/String;Lsystem/Object;)V
            // (LSystem/String;LSystem/String;LSystem/Text/Encoding;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RUtil.IO.FileWriteText(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, source), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, fileName), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Text.Encoding>(@__env, encode));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void WriteFile1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle filename, global::net.sf.jni4net.utils.JniLocalHandle contents) {
            // (Ljava/lang/String;Lsystem/collections/IEnumerable;)V
            // (LSystem/String;[[LSystem/Collections/Generic/IEnumerable`1;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RUtil.IO.WriteFile(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, filename), global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.Generic.IEnumerable<string>>(@__env, contents));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ReadFile2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle filename) {
            // (Ljava/lang/String;)Ljava/lang/String;
            // (LSystem/String;)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, global::RUtil.IO.ReadFile(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, filename)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ReadCSV3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle fileName, bool titleRaw) {
            // (Ljava/lang/String;Z)Lsystem/Object;
            // (LSystem/String;Z)[[[[[LSystem/Collections/Generic/Dictionary`2;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<object>>>(@__env, global::RUtil.IO.ReadCSV(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, fileName), titleRaw));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::RUtil.@__IO(@__env);
            }
        }
    }
    #endregion
}
