//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RUtil {
    
    
    #region Component Designer generated code 
    public partial class Utility_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::RUtil.@__Utility.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::RUtil.Utility), typeof(global::RUtil.Utility_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::RUtil.Utility), typeof(global::RUtil.Utility_))]
    internal sealed partial class @__Utility : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Utility(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::RUtil.@__Utility.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Utility);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetBaseTypes", "GetBaseTypes0", "(Lsystem/Type;)Lsystem/collections/IEnumerable;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "PadLeftInBytes", "PadLeftInBytes1", "(Ljava/lang/String;Lsystem/Enum;I)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "PadRightInBytes", "PadRightInBytes2", "(Ljava/lang/String;Lsystem/Enum;I)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Split", "Split3", "(Ljava/lang/String;ZCC)[Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Split", "Split4", "(Ljava/lang/String;Ljava/lang/String;Lsystem/Enum;)[Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Replace", "Replace5", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ParseInt", "ParseInt6", "(Ljava/lang/String;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ParseString", "ParseString7", "(Lsystem/collections/IEnumerable;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ParseDouble", "ParseDouble8", "(Ljava/lang/String;)D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Round", "Round9", "(D)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RoundDown", "RoundDown10", "(D)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RoundUp", "RoundUp11", "(D)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Div", "Div12", "(JJ)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Div", "Div13", "(DD)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToRadian", "ToRadian14", "(D)D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToAngle", "ToAngle15", "(D)D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToFraction", "ToFraction16", "(DLnet/sf/jni4net/Out;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Reduction", "Reduction17", "(JJ)Lsystem/ValueType;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Gcd", "Gcd18", "(JJ)J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "PrimeNumber", "PrimeNumber19", "(Lsystem/MulticastDelegate;)Lsystem/collections/IEnumerable;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Distance", "Distance20", "(DDDD)D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Toggle", "Toggle21", "(Lnet/sf/jni4net/Ref;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Not", "Not22", "(Z)Z"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetBaseTypes0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle self) {
            // (Lsystem/Type;)Lsystem/collections/IEnumerable;
            // (LSystem/Type;)[[LSystem/Collections/Generic/IEnumerable`1;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::System.Collections.IEnumerable>(@__env, Mitza.Jni4Net.Convertor.ToIEnumerable(global::RUtil.Utility.GetBaseTypes(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Type>(@__env, self))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle PadLeftInBytes1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle value, global::net.sf.jni4net.utils.JniLocalHandle type, int byteCount) {
            // (Ljava/lang/String;Lsystem/Enum;I)Ljava/lang/String;
            // (LSystem/String;LRUtil/Utility+PadType;I)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, global::RUtil.Utility.PadLeftInBytes(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, value), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::RUtil.Utility.PadType>(@__env, type), byteCount));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle PadRightInBytes2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle value, global::net.sf.jni4net.utils.JniLocalHandle type, int byteCount) {
            // (Ljava/lang/String;Lsystem/Enum;I)Ljava/lang/String;
            // (LSystem/String;LRUtil/Utility+PadType;I)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, global::RUtil.Utility.PadRightInBytes(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, value), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::RUtil.Utility.PadType>(@__env, type), byteCount));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Split3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle source, bool isArgs, char separator, char blocker) {
            // (Ljava/lang/String;ZCC)[Ljava/lang/String;
            // (LSystem/String;ZCC)[LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2JString(@__env, global::RUtil.Utility.Split(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, source), isArgs, separator, blocker));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Split4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle source, global::net.sf.jni4net.utils.JniLocalHandle pattern, global::net.sf.jni4net.utils.JniLocalHandle option) {
            // (Ljava/lang/String;Ljava/lang/String;Lsystem/Enum;)[Ljava/lang/String;
            // (LSystem/String;LSystem/String;LSystem/Text/RegularExpressions/RegexOptions;)[LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2JString(@__env, global::RUtil.Utility.Split(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, source), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, pattern), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Text.RegularExpressions.RegexOptions>(@__env, option)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Replace5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle source, global::net.sf.jni4net.utils.JniLocalHandle pattern, global::net.sf.jni4net.utils.JniLocalHandle replacement) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
            // (LSystem/String;LSystem/String;LSystem/String;)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, global::RUtil.Utility.Replace(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, source), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, pattern), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, replacement)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int ParseInt6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle source) {
            // (Ljava/lang/String;)I
            // (LSystem/String;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            @__return = ((int)(global::RUtil.Utility.ParseInt(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, source))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ParseString7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle source) {
            // (Lsystem/collections/IEnumerable;)Ljava/lang/String;
            // ([[LSystem/Collections/Generic/IEnumerable`1;)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, global::RUtil.Utility.ParseString(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.Generic.IEnumerable<char>>(@__env, source)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double ParseDouble8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle source) {
            // (Ljava/lang/String;)D
            // (LSystem/String;)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            @__return = ((double)(global::RUtil.Utility.ParseDouble(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, source))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int Round9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, double value) {
            // (D)I
            // (D)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            @__return = ((int)(global::RUtil.Utility.Round(value)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int RoundDown10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, double value) {
            // (D)I
            // (D)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            @__return = ((int)(global::RUtil.Utility.RoundDown(value)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int RoundUp11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, double value) {
            // (D)I
            // (D)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            @__return = ((int)(global::RUtil.Utility.RoundUp(value)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Div12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, long left, long right) {
            // (JJ)Lsystem/Object;
            // (JJ)[[[LSystem/Tuple`2;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Tuple<long, long>>(@__env, global::RUtil.Utility.Div(left, right));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Div13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, double left, double right) {
            // (DD)Lsystem/Object;
            // (DD)[[[LSystem/Tuple`2;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Tuple<double, double>>(@__env, global::RUtil.Utility.Div(left, right));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double ToRadian14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, double angle) {
            // (D)D
            // (D)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            @__return = ((double)(global::RUtil.Utility.ToRadian(angle)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double ToAngle15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, double radian) {
            // (D)D
            // (D)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            @__return = ((double)(global::RUtil.Utility.ToAngle(radian)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool ToFraction16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, double value, global::net.sf.jni4net.utils.JniLocalHandle result) {
            // (DLnet/sf/jni4net/Out;)Z
            // (D[[[LSystem/ValueTuple`2;)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.ValueTuple<long, long> @__out_result;
            @__return = ((bool)(global::RUtil.Utility.ToFraction(value, out __out_result)));
            net.sf.jni4net.Out.SetValue<global::System.ValueTuple<long, long>>(@__env, result, @__out_result);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Reduction17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, long numerator, long denominator) {
            // (JJ)Lsystem/ValueType;
            // (JJ)[[[LSystem/ValueTuple`2;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.ValueTuple<long, long>>(@__env, global::RUtil.Utility.Reduction(numerator, denominator));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long Gcd18(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, long a, long b) {
            // (JJ)J
            // (JJ)J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            @__return = ((long)(global::RUtil.Utility.Gcd(a, b)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle PrimeNumber19(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle conditions) {
            // (Lsystem/MulticastDelegate;)Lsystem/collections/IEnumerable;
            // ([[[LSystem/Func`2;)[[LSystem/Collections/Generic/IEnumerable`1;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::System.Collections.IEnumerable>(@__env, Mitza.Jni4Net.Convertor.ToIEnumerable(global::RUtil.Utility.PrimeNumber(global::net.sf.jni4net.utils.Convertor.StrongJ2CpDelegate<global::System.Func<int, bool>>(@__env, conditions))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Distance20(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, double x1, double y1, double x2, double y2) {
            // (DDDD)D
            // (DDDD)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            @__return = ((double)(global::RUtil.Utility.Distance(x1, y1, x2, y2)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool Toggle21(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lnet/sf/jni4net/Ref;)Z
            // (Z)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            bool @__ref_value = net.sf.jni4net.Ref.GetValue<bool>(@__env, value);
            @__return = ((bool)(global::RUtil.Utility.Toggle(ref __ref_value)));
            net.sf.jni4net.Ref.SetValue<bool>(@__env, value, @__ref_value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool Not22(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, bool value) {
            // (Z)Z
            // (Z)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            @__return = ((bool)(global::RUtil.Utility.Not(value)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::RUtil.@__Utility(@__env);
            }
        }
    }
    #endregion
}
